name: 'Install Octopus-CLI'
description: 'Installation of the Octopus CLI'

inputs:
  version:
    description: Version to install
    required: true

runs:
  using: node12
  main: dist/installoctocli.js