name: octocli

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:

  build:
    name: Install OctoCLI 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest, selfhosted]
    steps:
      - uses: actions/checkout@v2
      
      - name: install Octopus Deploy CLI
        uses: OctopusDeploy/install-octocli@v1
        with:
          version: 7.4.2

      - name: Test OctoCLI 
        run: octo version
        
