name: 'build-test'
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run all